# extra version information
#

BASE_VER= $(shell git describe --tags --match="v[0-9]*.[0-9]*.[0-9]*" --abbrev=0 HEAD 2>/dev/null)
TOP_VER = $(shell git describe --tags --match="v[0-9]*.[0-9]*.[0-9]*" --dirty 2>/dev/null)

EXTRA_LD_FLAGS= -X \"$(BEAT_PATH)/beater.baseVersion=$(BASE_VER)\" -X \"$(BEAT_PATH)/beater.topVersion=$(TOP_VER)\"

${BEAT_NAME}: Makefile.version
