name: Go Package
on: 
  pull_request:
    types: [closed]
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2
    
    - name: Get tags for ${{ github.repository }}
      run: git fetch --prune --unshallow --tags

    - name: Install make
      run: sudo apt-get install make
    
    - name: Install pcap
      run: sudo apt-get install libpcap0.8 libpcap0.8-dev
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2

    - name: Install mage
      run: |
           git clone https://github.com/magefile/mage
           cd mage
           go run bootstrap.go

    - name: Install docker 
      run: |
           sudo apt-get install runc containerd docker.io
           USER=`whoami`; sudo usermod -a -G docker $USER
    
    - name: Build on local machine
      run: |
           go env -w GONOPROXY="github.com/intuitivelabs" GONOSUMDB="github.com/intuitivelabs" GOPRIVATE="github.com/intuitivelabs"; go env
           go get
           make

    - name: Package (uses docker container)
      run: export PLATFORMS="linux/amd64"; export BEAT_NAME=sipcmbeat; export BEAT_GO_VERSION=1.15.12; make release

    - name: Archive packages
      uses: actions/upload-artifact@v2
      with:
        name: sipcmbeat-packages
        path: build/distributions/
